sudo: required
dist: trusty
# Force travis to use its minimal image with default Python settings
language: python

env:
  global:
    - ROS_DISTRO="indigo"
    - UPSTREAM_WORKSPACE=file
    - BEFORE_SCRIPT=./.travis.install.sh
    - NOT_TEST_INSTALL='true'

install:
  - git clone --depth=1 https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh 
